baseURL = "https://tinks.github.io/sample-docs-hugo/"
title = "Sample documentation"
# relativeURLs = true

[outputs]
  section = ["HTML","print"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "catppuccin-frappe"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      guessSyntax = false

[params]
  copyright = "tinks"

  # Enable local search
  offlineSearch = true
  prism_syntax_highlighting = false

[params.ui]
  sidebar_menu_compact = true
  sidebar_menu_foldable = true
  navbar_logo = true
  sidebar_search_disable = true

[params.links]
  [[params.links.user]]
    name = "Icons by Font Awesome"
    url = "https://fontawesome.com/"
    icon = "fa-solid fa-font-awesome"

[params.mermaid]
  enable = true
  theme = 'neutral'
  themeCSS = 'rect.actor { fill: #097E8C; stroke: #097E8C; } text.actor > tspan { fill: white; stroke: none; } .nodeLabel { font-size: 14px; } .edgeLabel { font-size: 14px; }'
  fontFamily = 'Courier'

[params.mermaid.sequence]
  diagramMarginX = 0
  diagramMarginY = 10
  actorMargin = 20
  width = 100
  height = 30
  boxMargin = 5
  boxTextMargin = 5
  mirrorActors = false
  useMaxWidth = true
  actorFontFamily = 'Courier'
  actorFontSize = '14px'
  actorFontWeight = 'bold'
  messageFontFamily = 'Courier'
  messageFontSize = '14px'
  noteFontFamily = 'Courier'
  noteFontSize = '14px'

[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    max = ""
    min = "0.148.0"
  [[module.imports]]
    path = "github.com/google/docsy"
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
  [[module.imports]]
    path = "github.com/rapi-doc/RapiDoc"
  [[module.imports.mounts]]
    source = "dist/rapidoc-min.js"
    target = "static/js/rapidoc-min.js"
